"""add composite indexes for analytics queries

Revision ID: 8f0a18288816
Revises: 5061d4ef9ce8
Create Date: 2026-07-27 16:52:47.885778

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f0a18288816"
down_revision: str | Sequence[str] | None = "5061d4ef9ce8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_log_timestamp_action", table_name="audit_log")
    op.drop_index(
        "ix_member_package_entitlements_member_id_status",
        table_name="member_package_entitlements",
    )
    op.drop_index("ix_reservations_seat_id_reserved_from", table_name="reservations")
    op.drop_index("ix_sessions_created_at", table_name="sessions")
    op.drop_index("ix_sessions_seat_id_status", table_name="sessions")
    op.drop_index("ix_sessions_shift_id", table_name="sessions")
    op.drop_index("ix_sessions_status_started_at", table_name="sessions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_sessions_status_started_at",
        "sessions",
        ["status", "started_at"],
        unique=False,
    )
    op.create_index("ix_sessions_shift_id", "sessions", ["shift_id"], unique=False)
    op.create_index(
        "ix_sessions_seat_id_status",
        "sessions",
        ["seat_id", "status"],
        unique=False,
    )
    op.create_index("ix_sessions_created_at", "sessions", ["created_at"], unique=False)
    op.create_index(
        "ix_reservations_seat_id_reserved_from",
        "reservations",
        ["seat_id", "reserved_from"],
        unique=False,
    )
    op.create_index(
        "ix_member_package_entitlements_member_id_status",
        "member_package_entitlements",
        ["member_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_timestamp_action",
        "audit_log",
        ["timestamp", "action"],
        unique=False,
    )
    # ### end Alembic commands ###
