"""add_wol_counters_to_seat

Revision ID: a1bb8b056ad6
Revises: b45fd59d442e
Create Date: 2026-07-03 15:44:55.557003

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1bb8b056ad6"
down_revision: str | Sequence[str] | None = "b45fd59d442e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seats",
        sa.Column("wol_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "seats",
        sa.Column("wol_successes", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "seats",
        sa.Column("wol_failures", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seats", "wol_failures")
    op.drop_column("seats", "wol_successes")
    op.drop_column("seats", "wol_attempts")
    # ### end Alembic commands ###
