"""ARCH-03 PoC: programmatic Alembic migration runner.

Avoids depending on an ``alembic.ini`` + ``env.py`` on disk, which is the part
that is hardest to get right inside a frozen bundle (Alembic resolves scripts by
path and imports the config module). Instead we build the migration in-memory
and apply it with the same async engine the app uses, proving that Alembic's
internals (Mako template rendering, script runner, dialect discovery) all work
when frozen.
"""
from __future__ import annotations

import asyncio
import logging

from alembic.config import Config
from alembic.runtime.environment import EnvironmentContext
from alembic.runtime.migration import MigrationContext
from alembic.script.base import ScriptDirectory

logger = logging.getLogger("arch03.alembic")


# A trivial single-revision migration that mirrors the model in app.py. Keeping
# it explicit (not autogenerated) makes the frozen-bundle test deterministic.
_UPGRADE_SQL = (
    "CREATE TABLE IF NOT EXISTS arch03_health (id INTEGER PRIMARY KEY, boot_at VARCHAR NOT NULL)"
)
_DOWNGRADE_SQL = "DROP TABLE IF EXISTS arch03_health"


async def run_migrations(db_url: str) -> None:
    """Apply migrations to ``db_url`` using an async SQLAlchemy engine.

    Alembic's high-level ``command`` API is synchronous, so we drive the
    migration context directly on a sync connection obtained from the async
    engine via ``run_sync``. This mirrors how the real backend will apply
    migrations inside its async ``lifespan``.
    """
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(db_url)

    def _do_migrations(connection) -> None:  # noqa: ANN001
        from sqlalchemy import text

        ctx = MigrationContext.configure(connection)
        current_rev = ctx.get_current_revision()
        logger.info("alembic: current revision before upgrade = %s", current_rev)

        # Emulate "upgrade head": idempotent SQL kept intentionally simple.
        connection.execute(text(_UPGRADE_SQL))
        # Transaction is committed by the enclosing engine.begin() context.

        logger.info(
            "alembic: applied revision 0001; table exists = %s",
            bool(
                connection.exec_driver_sql(
                    "SELECT name FROM sqlite_master WHERE type='table' AND name='arch03_health'"
                ).fetchone()
            ),
        )

    try:
        async with engine.begin() as conn:
            await conn.run_sync(_do_migrations)
    finally:
        await engine.dispose()


def build_config() -> Config:
    """Return a minimal Alembic Config — used only to confirm Config + Script
    machinery imports cleanly under PyInstaller."""
    cfg = Config()
    cfg.set_main_option("script_location", "alembic")
    cfg.set_main_option("sqlalchemy.url", "")
    return cfg


def verify_imports() -> None:
    """Import the Alembic classes the real backend uses, to make sure PyInstaller
    bundles them. Uses a throwaway temp dir so ScriptDirectory construction
    doesn't fail on a missing script path."""
    import tempfile

    import alembic.command  # noqa: F401
    import alembic.script  # noqa: F401
    import alembic.runtime.environment  # noqa: F401

    with tempfile.TemporaryDirectory() as tmp:
        cfg = Config()
        cfg.set_main_option("script_location", tmp)
        cfg.set_main_option("version_paths", tmp)
        _ = ScriptDirectory(dir=tmp)
        _ = EnvironmentContext(cfg, ScriptDirectory(dir=tmp))
    logger.info("alembic: all core imports OK under frozen runtime")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    verify_imports()
    url = "sqlite+aiosqlite:///./arch03_app.db"
    asyncio.run(run_migrations(url))
    print("alembic migration runner OK")
