"""Embedded Ed25519 public key for offline license verification.

This file is auto-generated by `tools/keygen/generate_keys.py`.
Do NOT edit the ARCADE_PUBLIC_KEY_HEX value by hand.

HOW TO REGENERATE THE KEYPAIR
------------------------------
  1. Run from repo root:
       python tools/keygen/generate_keys.py

  2. Commit ONLY the updated backend/licensing/public_key.py
     NEVER commit tools/keygen/private_key.pem to version control!

HOW TO SIGN A LICENSE
--------------------
  1. Get the Hardware ID from the target machine:
       python -c "from backend.licensing.fingerprint import get_hardware_id;"
       python -c "print(get_hardware_id())"

  2. Generate the license:
       python -m tools.keygen.generate_license \
         --hardware-id <32-hex-id> \
         --cafe-name  "Galaxy Gaming Lounge"

  3. This produces a signed `license.key` file. Deliver it to the customer.

HOW LICENSE VERIFICATION WORKS
------------------------------
  1. The Arcade launcher / server reads license.key at startup.
  2. It loads `ARCADE_PUBLIC_KEY_HEX` from this module.
  3. It verifies the Ed25519 signature on the license payload.
  4. It checks that the `hardware_id` in the payload matches the
     current machine (via `backend.licensing.fingerprint.get_hardware_id()`).
  5. If the license type is TRIAL, it also checks the expiry date.

SECURITY NOTES
--------------
  - The public key is baked into the distributed binary. It can VERIFY
    signatures, but cannot CREATE them.
  - The private key lives ONLY in tools/keygen/private_key.pem and is
    used ONLY by the internal `generate_license.py` script.
  - Guard the private key as you would any signing credential. Compromise
    of the private key allows creation of unauthorized licenses.
"""

ARCADE_PUBLIC_KEY_HEX: str = (
    "dd4346d6577d5e5c0d59943c0368bad8c2e3d16dcc787fdd5d1de8774ca26e93"
)
