"""Generate an Ed25519 keypair for the Arcade offline licensing system.

INTERNAL USE ONLY - Never commit or distribute private_key.pem.

This script generates a fresh Ed25519 keypair and stores:
  - Private key → tools/keygen/private_key.pem (keep secret!)
  - Public key  → backend/licensing/public_key.py (compiled into app)

Usage:
    python tools/keygen/generate_keys.py

After running, commit ONLY the updated public_key.py (not the .pem).
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    from nacl.signing import SigningKey
except ImportError as exc:  # pragma: no cover
    raise ImportError("PyNaCl is required: pip install PyNaCl") from exc


REPO_ROOT = Path(__file__).resolve().parents[2]
PRIVATE_KEY_PATH = REPO_ROOT / "tools" / "keygen" / "private_key.pem"
PUBLIC_KEY_PY = REPO_ROOT / "backend" / "licensing" / "public_key.py"


def generate_keypair() -> tuple[str, str]:
    """Generate a fresh Ed25519 keypair.

    Returns:
        (private_key_hex, public_key_hex) both as hex strings.
    """
    signing_key = SigningKey.generate()
    private_hex = signing_key.encode().hex()
    public_hex = signing_key.verify_key.encode().hex()
    return private_hex, public_hex


def write_private_key(private_hex: str) -> None:
    """Write the private key to private_key.pem."""
    PRIVATE_KEY_PATH.parent.mkdir(parents=True, exist_ok=True)
    PRIVATE_KEY_PATH.write_text(private_hex, encoding="utf-8")
    print(f"  Private key written to: {PRIVATE_KEY_PATH}")


def write_public_key_module(public_hex: str) -> None:
    """Write the public_key.py module with embedded public key."""
    content = PUBLIC_KEY_TEMPLATE.format(public_hex=public_hex)
    PUBLIC_KEY_PY.write_text(content, encoding="utf-8")
    print(f"  Public key module written to: {PUBLIC_KEY_PY}")


PUBLIC_KEY_TEMPLATE = '''"""Ed25519 public key for offline license verification.

This file is auto-generated by `tools/keygen/generate_keys.py`.
Do NOT edit the ARCADE_PUBLIC_KEY_HEX value by hand.

HOW TO REGENERATE THE KEYPAIR
------------------------------
  1. Run from repo root:
       python tools/keygen/generate_keys.py

  2. Commit ONLY the updated backend/licensing/public_key.py
     NEVER commit tools/keygen/private_key.pem to version control!

HOW TO SIGN A LICENSE
--------------------
  1. Get the Hardware ID from the target machine:
       python -c "from backend.licensing.fingerprint import get_hardware_id;"
       python -c "print(get_hardware_id())"

  2. Generate the license:
       python -m tools.keygen.generate_license \\
         --hardware-id <32-hex-id> \\
         --cafe-name  "Galaxy Gaming Lounge"

  3. This produces a signed `license.key` file. Deliver it to the customer.

HOW LICENSE VERIFICATION WORKS
------------------------------
  1. The Arcade launcher / server reads license.key at startup.
  2. It loads `ARCADE_PUBLIC_KEY_HEX` from this module.
  3. It verifies the Ed25519 signature on the license payload.
  4. It checks that the `hardware_id` in the payload matches the
     current machine (via `backend.licensing.fingerprint.get_hardware_id()`).
  5. If the license type is TRIAL, it also checks the expiry date.

SECURITY NOTES
--------------
  - The public key is baked into the distributed binary. It can VERIFY
    signatures, but cannot CREATE them.
  - The private key lives ONLY in tools/keygen/private_key.pem and is
    used ONLY by the internal `generate_license.py` script.
  - Guard the private key as you would any signing credential. Compromise
    of the private key allows creation of unauthorized licenses.
"""

ARCADE_PUBLIC_KEY_HEX: str = "{public_hex}"
'''


def main() -> int:
    """Generate keypair, write files, show next steps."""
    print("=" * 70)
    print("Arcade Ed25519 Keypair Generator")
    print("=" * 70)
    print()

    if PRIVATE_KEY_PATH.exists():
        print(f"WARNING: {PRIVATE_KEY_PATH} already exists.")
        print("This will OVERWRITE the existing keypair!")
        print()
        confirm = input("Continue? [y/N]: ").strip().lower()
        if confirm != "y":
            print("Aborted.")
            return 1
        print()

    private_hex, public_hex = generate_keypair()

    write_private_key(private_hex)
    write_public_key_module(public_hex)

    # ~/.gitignore already ignores *.pem via R-05 older config,
    # but guard for older repos just case
    gitignore = REPO_ROOT / ".gitignore"
    if gitignore.exists() and str(PRIVATE_KEY_PATH) not in gitignore.read_text():
        with gitignore.open("a") as f:
            f.write(f"\\n{PRIVATE_KEY_PATH}\\n")
            f.write("tools/keygen/private_key.pem\\n")
            print("  Added private_key.pem to .gitignore")

    print()
    print("Done!")
    print("Next steps:")
    print("  1. Add private_key.pem to .gitignore (if not already)")
    print("  2. Commit ONLY the updated backend/licensing/public_key.py")
    print("  3. NEVER commit tools/keygen/private_key.pem")
    print()
    print("Usage:")
    print("  python tools/keygen/generate_keys.py  # regenerate (caution)")
    print(
        "  python -m tools.keygen.generate_license "
        "--hardware-id <id> --cafe-name <name>"
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
