"""Generate an Ed25519 keypair for the Arcade offline licensing system.

INTERNAL USE ONLY - Never commit or distribute private_key.pem.

This script generates a fresh Ed25519 keypair and stores:
  - Private key → tools/keygen/private_key.pem (keep secret!)
  - Public key  → backend/licensing/public_key.py (compiled into app)

Usage:
    python tools/keygen/generate_keys.py

After running, commit ONLY the updated public_key.py (not the .pem).
"""

from __future__ import annotations

# ===========================================================================
# EMERGENCY MASTER PIN  (per-cafe, seller-only — NEVER shown in any UI)
# ---------------------------------------------------------------------------
# The Arcade Agent's emergency unlock PIN is the ONLY credential that works when
# the agent cannot reach the server (when connected, only the staff override
# PIN works). It is resolved at enrollment from ARCADE_MASTER_PIN, defaulting to
# '1928' (see agent/src/main/master-pin.ts + agent/.env.example), then hashed
# with Argon2id and stored as `master_code_hash` in agent.config.json.
#
# `generate_master_pin_hash()` below reproduces the SAME Argon2id parameters the
# agent uses at runtime (memory_cost=4096 KiB, time_cost=3, parallelism=1,
# hash_len=32, Argon2id) so a pre-baked hash and a runtime-computed hash are
# interchangeable. Use `--master-pin <PIN>` to print a hash for the seller's
# secure records (the REMEMBRANCE row below).
#
# REMEMBRANCE — fill one row per cafe and keep in the seller's secure notes:
#   Cafe: ____________   Master PIN: ____________   MASTER_PIN_HASH: ____________
# This file is internal tooling and must never be committed or shipped.
# ===========================================================================
import sys
from pathlib import Path

try:
    from nacl.signing import SigningKey
except ImportError as exc:  # pragma: no cover
    raise ImportError("PyNaCl is required: pip install PyNaCl") from exc


REPO_ROOT = Path(__file__).resolve().parents[2]
PRIVATE_KEY_PATH = REPO_ROOT / "tools" / "keygen" / "private_key.pem"
PUBLIC_KEY_PY = REPO_ROOT / "backend" / "licensing" / "public_key.py"


def generate_keypair() -> tuple[str, str]:
    """Generate a fresh Ed25519 keypair.

    Returns:
        (private_key_hex, public_key_hex) both as hex strings.
    """
    signing_key = SigningKey.generate()
    private_hex = signing_key.encode().hex()
    public_hex = signing_key.verify_key.encode().hex()
    return private_hex, public_hex


# Argon2id parameters MUST match the agent runtime (agent/src/main/enroll.ts
# MASTER_PIN_HASH_OPTIONS). @node-rs/argon2 defaults are memoryCost=4096,
# timeCost=3, parallelism=1, hash_len=32, algorithm=Argon2id.
_MASTER_PIN_ARGON2_PARAMS = {
    "memory_cost": 4096,
    "time_cost": 3,
    "parallelism": 1,
    "hash_len": 32,
}


def generate_master_pin_hash(pin: str) -> str:
    """Hash a master PIN with Argon2id using the agent's runtime parameters.

    The agent computes this same hash at enrollment; a hash produced here is
    byte-for-byte compatible (verify() reads the params from the stored hash).
    Requires `argon2-cffi` (pip install argon2-cffi).

    Args:
        pin: The plaintext master PIN (e.g. "1928").

    Returns:
        An Argon2id PHC hash string (e.g. "$argon2id$v=19$m=4096,t=3,p=1$...").
    """
    try:
        from argon2 import PasswordHasher
        from argon2.low_level import Type
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "argon2-cffi is required to generate a master PIN hash: "
            "pip install argon2-cffi"
        ) from exc

    ph = PasswordHasher(type=Type.ID, **_MASTER_PIN_ARGON2_PARAMS)
    return ph.hash(pin)


def write_private_key(private_hex: str) -> None:
    """Write the private key to private_key.pem."""
    PRIVATE_KEY_PATH.parent.mkdir(parents=True, exist_ok=True)
    PRIVATE_KEY_PATH.write_text(private_hex, encoding="utf-8")
    print(f"  Private key written to: {PRIVATE_KEY_PATH}")


def write_public_key_module(public_hex: str) -> None:
    """Write the public_key.py module with embedded public key."""
    content = PUBLIC_KEY_TEMPLATE.format(public_hex=public_hex)
    PUBLIC_KEY_PY.write_text(content, encoding="utf-8")
    print(f"  Public key module written to: {PUBLIC_KEY_PY}")


PUBLIC_KEY_TEMPLATE = '''"""Ed25519 public key for offline license verification.

This file is auto-generated by `tools/keygen/generate_keys.py`.
Do NOT edit the ARCADE_PUBLIC_KEY_HEX value by hand.

HOW TO REGENERATE THE KEYPAIR
------------------------------
  1. Run from repo root:
       python tools/keygen/generate_keys.py

  2. Commit ONLY the updated backend/licensing/public_key.py
     NEVER commit tools/keygen/private_key.pem to version control!

HOW TO SIGN A LICENSE
--------------------
  1. Get the Hardware ID from the target machine:
       python -c "from backend.licensing.fingerprint import get_hardware_id;"
       python -c "print(get_hardware_id())"

  2. Generate the license (choose one):
       CLI:
         python -m tools.keygen.generate_license \\
           --hardware-id <32-hex-id> \\
           --cafe-name  "Galaxy Gaming Lounge"
       GUI (no args needed):
         python -m tools.keygen.generate_license --gui
         # then fill the form and click Generate License

  3. This produces a signed `license.key` file. Deliver it to the customer.

HOW LICENSE VERIFICATION WORKS
------------------------------
  1. The Arcade launcher / server reads license.key at startup.
  2. It loads `ARCADE_PUBLIC_KEY_HEX` from this module.
  3. It verifies the Ed25519 signature on the license payload.
  4. It checks that the `hardware_id` in the payload matches the
     current machine (via `backend.licensing.fingerprint.get_hardware_id()`).
  5. If the license type is TRIAL, it also checks the expiry date.

SECURITY NOTES
--------------
  - The public key is baked into the distributed binary. It can VERIFY
    signatures, but cannot CREATE them.
  - The private key lives ONLY in tools/keygen/private_key.pem and is
    used ONLY by the internal `generate_license.py` script.
  - Guard the private key as you would any signing credential. Compromise
    of the private key allows creation of unauthorized licenses.
"""

ARCADE_PUBLIC_KEY_HEX: str = "{public_hex}"
'''


def main() -> int:
    """Generate keypair, write files, show next steps."""
    # --- Optional master PIN hash generation (--master-pin <PIN>) ---
    master_pin: str | None = None
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--master-pin":
            master_pin = args[i + 1] if i + 1 < len(args) else ""
            i += 2 if i + 1 < len(args) else 1
            continue
        if a.startswith("--master-pin="):
            master_pin = a.split("=", 1)[1]
            i += 1
            continue
        i += 1

    print("=" * 70)
    print("Arcade Ed25519 Keypair Generator")
    print("=" * 70)
    print()

    if PRIVATE_KEY_PATH.exists():
        print(f"WARNING: {PRIVATE_KEY_PATH} already exists.")
        print("This will OVERWRITE the existing keypair!")
        print()
        confirm = input("Continue? [y/N]: ").strip().lower()
        if confirm != "y":
            print("Aborted.")
            return 1
        print()

    private_hex, public_hex = generate_keypair()

    write_private_key(private_hex)
    write_public_key_module(public_hex)

    # ~/.gitignore already ignores *.pem via R-05 older config,
    # but guard for older repos just case
    gitignore = REPO_ROOT / ".gitignore"
    if gitignore.exists() and str(PRIVATE_KEY_PATH) not in gitignore.read_text():
        with gitignore.open("a") as f:
            f.write(f"\\n{PRIVATE_KEY_PATH}\\n")
            f.write("tools/keygen/private_key.pem\\n")
            print("  Added private_key.pem to .gitignore")

    # --- Emergency master PIN hash (optional) ---
    if master_pin is not None:
        print()
        if master_pin == "":
            print("Emergency master PIN: DISABLED (blank --master-pin).")
        else:
            try:
                h = generate_master_pin_hash(master_pin)
                print("Emergency master PIN hash (Argon2id, m=4096 t=3 p=1):")
                print(f"  {h}")
                print("This matches what the agent computes at enrollment for the")
                print("same PIN. Record it in the seller's secure REMEMBRANCE notes.")
            except ImportError as exc:
                print(f"  SKIPPED: {exc}")

    print()
    print("Done!")
    print("Next steps:")
    print("  1. Add private_key.pem to .gitignore (if not already)")
    print("  2. Commit ONLY the updated backend/licensing/public_key.py")
    print("  3. NEVER commit tools/keygen/private_key.pem")
    print()
    print("Usage:")
    print("  python tools/keygen/generate_keys.py  # regenerate (caution)")
    print(
        "  python -m tools.keygen.generate_license "
        "--hardware-id <id> --cafe-name <name>"
    )
    print("  python tools/keygen/generate_keys.py --master-pin 1928  # hash a PIN")

    return 0


if __name__ == "__main__":
    sys.exit(main())
